
front.url=http://localhost:4200

spring.application.name=api
server.servlet.context-path=/api/v1
spring.profiles.active=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.username=${POSTGRES_USER}
spring.jpa.hibernate.ddl-auto=update
spring.devtools.restart.enabled=false

# JWT properties
jwt.secret=xvnzsgK0/IuCursMWG+qa6bLDOUtCLSBbGJn4Kr3NmQ=
jwt.expiration=3600000

springdoc.swagger-ui.supported-submit-methods=get,head

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui