#spring.mongodb.uri=mongodb://mongo:27017/portfolio
spring.devtools.add-properties=false
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.password=password
spring.datasource.username=user

spring.devtools.restart.enabled=true

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.hbm2ddl=DEBUG