front.url=https://portfolio.peron-nicolas.com
back.url=https://portfolio.peron-nicolas.com/api/v1

cookie.domain=peron-nicolas.com
cookie.secure=true

spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.devtools.restart.enabled=false

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false