front.url=http://localhost:4200
back.url=http://localhost:8080/api/v1/

cookie.domain=localhost
cookie.secure=false

spring.devtools.add-properties=false
spring.datasource.url=jdbc:postgresql://postgres:5432/portfolio
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.devtools.restart.enabled=true
spring.jpa.show-sql=true

springdoc.swagger-ui.supported-submit-methods=*