
front.url=http://localhost:4200
cookie.domain=peron-nicolas.com
cookie.secure=true

spring.application.name=api
server.servlet.context-path=/api/v1
spring.profiles.active=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.username=${POSTGRES_USER}
spring.jpa.hibernate.ddl-auto=update
spring.devtools.restart.enabled=false

spring.jackson.property-naming-strategy=SNAKE_CASE

# JWT properties
jwt.secret=xvnzsgK0/IuCursMWG+qa6bLDOUtCLSBbGJn4Kr3NmQ=
jwt.expiration=3600000
jwt.refresh-token-path=/api/v1/auth

# Swagger configuration
springdoc.swagger-ui.supported-submit-methods=-1
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

# Storage
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB