DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PROJECT_SKILL;
DROP TABLE IF EXISTS IMAGE;
DROP TABLE IF EXISTS SKILL;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE IF NOT EXISTS USERS  (
    ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SKILL  (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    PERCENTAGE SMALLINT
);

CREATE TABLE IF NOT EXISTS PROJECT  (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    URL VARCHAR(255),
    IS_GITHUB BOOLEAN NOT NULL,
    SHORT_DESCRIPTION TEXT,
    DESCRIPTION TEXT,
    DATE_START DATE NOT NULL,
    DATE_END DATE,
    CATEGORY_ID BIGINT REFERENCES PROJECT(id),
    PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE IF NOT EXISTS IMAGE  (
    ID BIGSERIAL PRIMARY KEY,
    PATH VARCHAR(255) NOT NULL,
    ENTITY_TYPE VARCHAR(255) NOT NULL,
    ENTITY_ID BIGSERIAL NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJECT_SKILL (
    PROJECT_ID BIGINT REFERENCES PROJECT(id) ON DELETE CASCADE,
    SKILL_ID BIGINT REFERENCES SKILL(id) ON DELETE CASCADE,
    PRIMARY KEY (PROJECT_ID, SKILL_ID)
);

CREATE TABLE IF NOT EXISTS CATEGORY (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);